# Generated by Django 4.1.2 on 2022-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
