# Generated by Django 4.1.2 on 2022-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_diary', '0003_alter_training_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='date',
            field=models.DateTimeField(blank=True, default='2022-10-17', null=True),
        ),
    ]
