# Generated by Django 4.1.2 on 2022-10-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_diary', '0004_alter_training_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='number_of_sets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
